const char *class_name[1000] = {
    "tench",                 // 0
    "goldfish",              // 1
    "great",                 // 2
    "tiger",                 // 3
    "hammerhead",            // 4
    "electric",              // 5
    "stingray",              // 6
    "cock",                  // 7
    "hen",                   // 8
    "ostrich",               // 9
    "brambling",             // 10
    "goldfinch",             // 11
    "house",                 // 12
    "junco",                 // 13
    "indigo",                // 14
    "robin",                 // 15
    "bulbul",                // 16
    "jay",                   // 17
    "magpie",                // 18
    "chickadee",             // 19
    "water",                 // 20
    "kite",                  // 21
    "bald",                  // 22
    "vulture",               // 23
    "great",                 // 24
    "European",              // 25
    "common",                // 26
    "eft",                   // 27
    "spotted",               // 28
    "axolotl",               // 29
    "bullfrog",              // 30
    "tree",                  // 31
    "tailed",                // 32
    "loggerhead",            // 33
    "leatherback",           // 34
    "mud",                   // 35
    "terrapin",              // 36
    "box",                   // 37
    "banded",                // 38
    "common",                // 39
    "American",              // 40
    "whiptail",              // 41
    "agama",                 // 42
    "frilled",               // 43
    "alligator",             // 44
    "Gila",                  // 45
    "green",                 // 46
    "African",               // 47
    "Komodo",                // 48
    "African",               // 49
    "American",              // 50
    "triceratops",           // 51
    "thunder",               // 52
    "ringneck",              // 53
    "hognose",               // 54
    "green",                 // 55
    "king",                  // 56
    "garter",                // 57
    "water",                 // 58
    "vine",                  // 59
    "night",                 // 60
    "boa",                   // 61
    "rock",                  // 62
    "Indian",                // 63
    "green",                 // 64
    "sea",                   // 65
    "horned",                // 66
    "diamondback",           // 67
    "sidewinder",            // 68
    "trilobite",             // 69
    "harvestman",            // 70
    "scorpion",              // 71
    "black",                 // 72
    "barn",                  // 73
    "garden",                // 74
    "black",                 // 75
    "tarantula",             // 76
    "wolf",                  // 77
    "tick",                  // 78
    "centipede",             // 79
    "black",                 // 80
    "ptarmigan",             // 81
    "ruffed",                // 82
    "prairie",               // 83
    "peacock",               // 84
    "quail",                 // 85
    "partridge",             // 86
    "African",               // 87
    "macaw",                 // 88
    "sulphur-crested",       // 89
    "lorikeet",              // 90
    "coucal",                // 91
    "bee",                   // 92
    "hornbill",              // 93
    "hummingbird",           // 94
    "jacamar",               // 95
    "toucan",                // 96
    "drake",                 // 97
    "red-breasted",          // 98
    "goose",                 // 99
    "black",                 // 100
    "tusker",                // 101
    "echidna",               // 102
    "platypus",              // 103
    "wallaby",               // 104
    "koala",                 // 105
    "wombat",                // 106
    "jellyfish",             // 107
    "sea",                   // 108
    "brain",                 // 109
    "flatworm",              // 110
    "nematode",              // 111
    "conch",                 // 112
    "snail",                 // 113
    "slug",                  // 114
    "sea",                   // 115
    "chiton",                // 116
    "chambered",             // 117
    "Dungeness",             // 118
    "rock",                  // 119
    "fiddler",               // 120
    "king",                  // 121
    "American",              // 122
    "spiny",                 // 123
    "crayfish",              // 124
    "hermit",                // 125
    "isopod",                // 126
    "white",                 // 127
    "black",                 // 128
    "spoonbill",             // 129
    "flamingo",              // 130
    "little",                // 131
    "American",              // 132
    "bittern",               // 133
    "crane",                 // 134
    "limpkin",               // 135
    "European",              // 136
    "American",              // 137
    "bustard",               // 138
    "ruddy",                 // 139
    "red-backed",            // 140
    "redshank",              // 141
    "dowitcher",             // 142
    "oystercatcher",         // 143
    "pelican",               // 144
    "king",                  // 145
    "albatross",             // 146
    "grey",                  // 147
    "killer",                // 148
    "dugong",                // 149
    "sea",                   // 150
    "Chihuahua",             // 151
    "Japanese",              // 152
    "Maltese",               // 153
    "Pekinese",              // 154
    "Shih-Tzu",              // 155
    "Blenheim",              // 156
    "papillon",              // 157
    "toy",                   // 158
    "Rhodesian",             // 159
    "Afghan",                // 160
    "basset",                // 161
    "beagle",                // 162
    "bloodhound",            // 163
    "bluetick",              // 164
    "black-and-tan",         // 165
    "Walker",                // 166
    "English",               // 167
    "redbone",               // 168
    "borzoi",                // 169
    "Irish",                 // 170
    "Italian",               // 171
    "whippet",               // 172
    "Ibizan",                // 173
    "Norwegian",             // 174
    "otterhound",            // 175
    "Saluki",                // 176
    "Scottish",              // 177
    "Weimaraner",            // 178
    "Staffordshire",         // 179
    "American",              // 180
    "Bedlington",            // 181
    "Border",                // 182
    "Kerry",                 // 183
    "Irish",                 // 184
    "Norfolk",               // 185
    "Norwich",               // 186
    "Yorkshire",             // 187
    "wire-haired",           // 188
    "Lakeland",              // 189
    "Sealyham",              // 190
    "Airedale",              // 191
    "cairn",                 // 192
    "Australian",            // 193
    "Dandie",                // 194
    "Boston",                // 195
    "miniature",             // 196
    "giant",                 // 197
    "standard",              // 198
    "Scotch",                // 199
    "Tibetan",               // 200
    "silky",                 // 201
    "soft-coated",           // 202
    "West",                  // 203
    "Lhasa",                 // 204
    "flat-coated",           // 205
    "curly-coated",          // 206
    "golden",                // 207
    "Labrador",              // 208
    "Chesapeake",            // 209
    "German",                // 210
    "vizsla",                // 211
    "English",               // 212
    "Irish",                 // 213
    "Gordon",                // 214
    "Brittany",              // 215
    "clumber",               // 216
    "English",               // 217
    "Welsh",                 // 218
    "cocker",                // 219
    "Sussex",                // 220
    "Irish",                 // 221
    "kuvasz",                // 222
    "schipperke",            // 223
    "groenendael",           // 224
    "malinois",              // 225
    "briard",                // 226
    "kelpie",                // 227
    "komondor",              // 228
    "Old",                   // 229
    "Shetland",              // 230
    "collie",                // 231
    "Border",                // 232
    "Bouvier",               // 233
    "Rottweiler",            // 234
    "German",                // 235
    "Doberman",              // 236
    "miniature",             // 237
    "Greater",               // 238
    "Bernese",               // 239
    "Appenzeller",           // 240
    "EntleBucher",           // 241
    "boxer",                 // 242
    "bull",                  // 243
    "Tibetan",               // 244
    "French",                // 245
    "Great",                 // 246
    "Saint",                 // 247
    "Eskimo",                // 248
    "malamute",              // 249
    "Siberian",              // 250
    "dalmatian",             // 251
    "affenpinscher",         // 252
    "basenji",               // 253
    "pug",                   // 254
    "Leonberg",              // 255
    "Newfoundland",          // 256
    "Great",                 // 257
    "Samoyed",               // 258
    "Pomeranian",            // 259
    "chow",                  // 260
    "keeshond",              // 261
    "Brabancon",             // 262
    "Pembroke",              // 263
    "Cardigan",              // 264
    "toy",                   // 265
    "miniature",             // 266
    "standard",              // 267
    "Mexican",               // 268
    "timber",                // 269
    "white",                 // 270
    "red",                   // 271
    "coyote",                // 272
    "dingo",                 // 273
    "dhole",                 // 274
    "African",               // 275
    "hyena",                 // 276
    "red",                   // 277
    "kit",                   // 278
    "Arctic",                // 279
    "grey",                  // 280
    "tabby",                 // 281
    "tiger",                 // 282
    "Persian",               // 283
    "Siamese",               // 284
    "Egyptian",              // 285
    "cougar",                // 286
    "lynx",                  // 287
    "leopard",               // 288
    "snow",                  // 289
    "jaguar",                // 290
    "lion",                  // 291
    "tiger",                 // 292
    "cheetah",               // 293
    "brown",                 // 294
    "American",              // 295
    "ice",                   // 296
    "sloth",                 // 297
    "mongoose",              // 298
    "meerkat",               // 299
    "tiger",                 // 300
    "ladybug",               // 301
    "ground",                // 302
    "long-horned",           // 303
    "leaf",                  // 304
    "dung",                  // 305
    "rhinoceros",            // 306
    "weevil",                // 307
    "fly",                   // 308
    "bee",                   // 309
    "ant",                   // 310
    "grasshopper",           // 311
    "cricket",               // 312
    "walking",               // 313
    "cockroach",             // 314
    "mantis",                // 315
    "cicada",                // 316
    "leafhopper",            // 317
    "lacewing",              // 318
    "dragonfly",             // 319
    "damselfly",             // 320
    "admiral",               // 321
    "ringlet",               // 322
    "monarch",               // 323
    "cabbage",               // 324
    "sulphur",               // 325
    "lycaenid",              // 326
    "starfish",              // 327
    "sea",                   // 328
    "sea",                   // 329
    "wood",                  // 330
    "hare",                  // 331
    "Angora",                // 332
    "hamster",               // 333
    "porcupine",             // 334
    "fox",                   // 335
    "marmot",                // 336
    "beaver",                // 337
    "guinea",                // 338
    "sorrel",                // 339
    "zebra",                 // 340
    "hog",                   // 341
    "wild",                  // 342
    "warthog",               // 343
    "hippopotamus",          // 344
    "ox",                    // 345
    "water",                 // 346
    "bison",                 // 347
    "ram",                   // 348
    "bighorn",               // 349
    "ibex",                  // 350
    "hartebeest",            // 351
    "impala",                // 352
    "gazelle",               // 353
    "Arabian",               // 354
    "llama",                 // 355
    "weasel",                // 356
    "mink",                  // 357
    "polecat",               // 358
    "black-footed",          // 359
    "otter",                 // 360
    "skunk",                 // 361
    "badger",                // 362
    "armadillo",             // 363
    "three-toed",            // 364
    "orangutan",             // 365
    "gorilla",               // 366
    "chimpanzee",            // 367
    "gibbon",                // 368
    "siamang",               // 369
    "guenon",                // 370
    "patas",                 // 371
    "baboon",                // 372
    "macaque",               // 373
    "langur",                // 374
    "colobus",               // 375
    "proboscis",             // 376
    "marmoset",              // 377
    "capuchin",              // 378
    "howler",                // 379
    "titi",                  // 380
    "spider",                // 381
    "squirrel",              // 382
    "Madagascar",            // 383
    "indri",                 // 384
    "Indian",                // 385
    "African",               // 386
    "lesser",                // 387
    "giant",                 // 388
    "barracouta",            // 389
    "eel",                   // 390
    "coho",                  // 391
    "rock",                  // 392
    "anemone",               // 393
    "sturgeon",              // 394
    "gar",                   // 395
    "lionfish",              // 396
    "puffer",                // 397
    "abacus",                // 398
    "abaya",                 // 399
    "academic",              // 400
    "accordion",             // 401
    "acoustic",              // 402
    "aircraft",              // 403
    "airliner",              // 404
    "airship",               // 405
    "altar",                 // 406
    "check",                 // 407
    "check",                 // 408
    "analog",                // 409
    "apiary",                // 410
    "apron",                 // 411
    "ashcan",                // 412
    "assault",               // 413
    "backpack",              // 414
    "bakery",                // 415
    "balance",               // 416
    "balloon",               // 417
    "ballpoint",             // 418
    "Band",                  // 419
    "banjo",                 // 420
    "bannister",             // 421
    "barbell",               // 422
    "barber",                // 423
    "barbershop",            // 424
    "barn",                  // 425
    "barometer",             // 426
    "barrel",                // 427
    "barrow",                // 428
    "baseball",              // 429
    "basketball",            // 430
    "bassinet",              // 431
    "bassoon",               // 432
    "bathing",               // 433
    "bath",                  // 434
    "bathtub",               // 435
    "check",                 // 436
    "beacon",                // 437
    "beaker",                // 438
    "bearskin",              // 439
    "beer",                  // 440
    "beer",                  // 441
    "bell",                  // 442
    "bib",                   // 443
    "bicycle-built-for-two", // 444
    "bikini",                // 445
    "binder",                // 446
    "binoculars",            // 447
    "birdhouse",             // 448
    "boathouse",             // 449
    "bobsled",               // 450
    "bolo",                  // 451
    "bonnet",                // 452
    "bookcase",              // 453
    "bookshop",              // 454
    "bottlecap",             // 455
    "bow",                   // 456
    "bow",                   // 457
    "brass",                 // 458
    "brassiere",             // 459
    "breakwater",            // 460
    "breastplate",           // 461
    "broom",                 // 462
    "bucket",                // 463
    "buckle",                // 464
    "bulletproof",           // 465
    "bullet",                // 466
    "butcher",               // 467
    "check",                 // 468
    "caldron",               // 469
    "candle",                // 470
    "cannon",                // 471
    "canoe",                 // 472
    "can",                   // 473
    "cardigan",              // 474
    "car",                   // 475
    "carousel",              // 476
    "carpenter’s",           // 477
    "carton",                // 478
    "car",                   // 479
    "cash",                  // 480
    "cassette",              // 481
    "cassette",              // 482
    "castle",                // 483
    "catamaran",             // 484
    "CD",                    // 485
    "cello",                 // 486
    "cellular",              // 487
    "chain",                 // 488
    "chainlink",             // 489
    "chain",                 // 490
    "chain",                 // 491
    "chest",                 // 492
    "chiffonier",            // 493
    "chime",                 // 494
    "china",                 // 495
    "Christmas",             // 496
    "church",                // 497
    "cinema",                // 498
    "cleaver",               // 499
    "cliff",                 // 500
    "cloak",                 // 501
    "clog",                  // 502
    "cocktail",              // 503
    "coffee",                // 504
    "coffeepot",             // 505
    "coil",                  // 506
    "combination",           // 507
    "computer",              // 508
    "confectionery",         // 509
    "container",             // 510
    "check",                 // 511
    "corkscrew",             // 512
    "cornet",                // 513
    "cowboy",                // 514
    "cowboy",                // 515
    "cradle",                // 516
    "crane",                 // 517
    "crash",                 // 518
    "crate",                 // 519
    "crib",                  // 520
    "Crock",                 // 521
    "croquet",               // 522
    "crutch",                // 523
    "cuirass",               // 524
    "dam",                   // 525
    "desk",                  // 526
    "desktop",               // 527
    "dial",                  // 528
    "diaper",                // 529
    "digital",               // 530
    "digital",               // 531
    "dining",                // 532
    "dishrag",               // 533
    "dishwasher",            // 534
    "disk",                  // 535
    "dock",                  // 536
    "dogsled",               // 537
    "dome",                  // 538
    "doormat",               // 539
    "drilling",              // 540
    "drum",                  // 541
    "drumstick",             // 542
    "dumbbell",              // 543
    "Dutch",                 // 544
    "electric",              // 545
    "electric",              // 546
    "check",                 // 547
    "entertainment",         // 548
    "envelope",              // 549
    "espresso",              // 550
    "face",                  // 551
    "feather",               // 552
    "file",                  // 553
    "fireboat",              // 554
    "check",                 // 555
    "fire",                  // 556
    "flagpole",              // 557
    "flute",                 // 558
    "folding",               // 559
    "football",              // 560
    "forklift",              // 561
    "fountain",              // 562
    "fountain",              // 563
    "four-poster",           // 564
    "freight",               // 565
    "French",                // 566
    "frying",                // 567
    "fur",                   // 568
    "check",                 // 569
    "gasmask",               // 570
    "gas",                   // 571
    "goblet",                // 572
    "go-kart",               // 573
    "golf",                  // 574
    "golfcart",              // 575
    "gondola",               // 576
    "gong",                  // 577
    "gown",                  // 578
    "grand",                 // 579
    "greenhouse",            // 580
    "check",                 // 581
    "grocery",               // 582
    "guillotine",            // 583
    "hair",                  // 584
    "hair",                  // 585
    "half",                  // 586
    "hammer",                // 587
    "hamper",                // 588
    "hand",                  // 589
    "hand-held",             // 590
    "handkerchief",          // 591
    "hard",                  // 592
    "harmonica",             // 593
    "harp",                  // 594
    "harvester",             // 595
    "hatchet",               // 596
    "holster",               // 597
    "home",                  // 598
    "honeycomb",             // 599
    "hook",                  // 600
    "hoopskirt",             // 601
    "horizontal",            // 602
    "horse",                 // 603
    "hourglass",             // 604
    "iPod",                  // 605
    "iron",                  // 606
    "jack-o'-lantern",       // 607
    "jean",                  // 608
    "check",                 // 609
    "jersey",                // 610
    "jigsaw",                // 611
    "jinrikisha",            // 612
    "joystick",              // 613
    "kimono",                // 614
    "knee",                  // 615
    "knot",                  // 616
    "lab",                   // 617
    "ladle",                 // 618
    "lampshade",             // 619
    "laptop",                // 620
    "lawn",                  // 621
    "lens",                  // 622
    "letter",                // 623
    "library",               // 624
    "lifeboat",              // 625
    "lighter",               // 626
    "check",                 // 627
    "liner",                 // 628
    "lipstick",              // 629
    "Loafer",                // 630
    "lotion",                // 631
    "loudspeaker",           // 632
    "loupe",                 // 633
    "lumbermill",            // 634
    "magnetic",              // 635
    "mailbag",               // 636
    "mailbox",               // 637
    "maillot",               // 638
    "maillot",               // 639
    "manhole",               // 640
    "maraca",                // 641
    "marimba",               // 642
    "mask",                  // 643
    "matchstick",            // 644
    "maypole",               // 645
    "maze",                  // 646
    "measuring",             // 647
    "medicine",              // 648
    "megalith",              // 649
    "microphone",            // 650
    "microwave",             // 651
    "military",              // 652
    "milk",                  // 653
    "check",                 // 654
    "miniskirt",             // 655
    "check",                 // 656
    "missile",               // 657
    "mitten",                // 658
    "mixing",                // 659
    "mobile",                // 660
    "Model",                 // 661
    "modem",                 // 662
    "monastery",             // 663
    "monitor",               // 664
    "check",                 // 665
    "mortar",                // 666
    "mortarboard",           // 667
    "mosque",                // 668
    "mosquito",              // 669
    "check",                 // 670
    "check",                 // 671
    "mountain",              // 672
    "mouse",                 // 673
    "mousetrap",             // 674
    "check",                 // 675
    "muzzle",                // 676
    "nail",                  // 677
    "neck",                  // 678
    "necklace",              // 679
    "nipple",                // 680
    "notebook",              // 681
    "obelisk",               // 682
    "oboe",                  // 683
    "ocarina",               // 684
    "odometer",              // 685
    "oil",                   // 686
    "organ",                 // 687
    "oscilloscope",          // 688
    "overskirt",             // 689
    "oxcart",                // 690
    "oxygen",                // 691
    "packet",                // 692
    "paddle",                // 693
    "paddlewheel",           // 694
    "padlock",               // 695
    "paintbrush",            // 696
    "pajama",                // 697
    "palace",                // 698
    "panpipe",               // 699
    "paper",                 // 700
    "parachute",             // 701
    "parallel",              // 702
    "park",                  // 703
    "parking",               // 704
    "check",                 // 705
    "patio",                 // 706
    "pay-phone",             // 707
    "pedestal",              // 708
    "pencil",                // 709
    "pencil",                // 710
    "perfume",               // 711
    "Petri",                 // 712
    "photocopier",           // 713
    "pick",                  // 714
    "pickelhaube",           // 715
    "picket",                // 716
    "check",                 // 717
    "pier",                  // 718
    "piggy",                 // 719
    "pill",                  // 720
    "pillow",                // 721
    "ping-pong",             // 722
    "pinwheel",              // 723
    "pirate",                // 724
    "pitcher",               // 725
    "plane",                 // 726
    "planetarium",           // 727
    "plastic",               // 728
    "plate",                 // 729
    "plow",                  // 730
    "plunger",               // 731
    "Polaroid",              // 732
    "pole",                  // 733
    "check",                 // 734
    "poncho",                // 735
    "pool",                  // 736
    "pop",                   // 737
    "pot",                   // 738
    "potter’s",              // 739
    "power",                 // 740
    "prayer",                // 741
    "printer",               // 742
    "prison",                // 743
    "projectile",            // 744
    "projector",             // 745
    "puck",                  // 746
    "punching",              // 747
    "purse",                 // 748
    "quill",                 // 749
    "quilt",                 // 750
    "racer",                 // 751
    "racket",                // 752
    "radiator",              // 753
    "radio",                 // 754
    "radio",                 // 755
    "rain",                  // 756
    "recreational",          // 757
    "reel",                  // 758
    "reflex",                // 759
    "refrigerator",          // 760
    "remote",                // 761
    "restaurant",            // 762
    "revolver",              // 763
    "rifle",                 // 764
    "rocking",               // 765
    "rotisserie",            // 766
    "rubber",                // 767
    "rugby",                 // 768
    "rule",                  // 769
    "running",               // 770
    "safe",                  // 771
    "safety",                // 772
    "saltshaker",            // 773
    "sandal",                // 774
    "sarong",                // 775
    "sax",                   // 776
    "scabbard",              // 777
    "scale",                 // 778
    "school",                // 779
    "schooner",              // 780
    "scoreboard",            // 781
    "screen",                // 782
    "screw",                 // 783
    "screwdriver",           // 784
    "seat",                  // 785
    "sewing",                // 786
    "shield",                // 787
    "shoe",                  // 788
    "shoji",                 // 789
    "shopping",              // 790
    "shopping",              // 791
    "shovel",                // 792
    "shower",                // 793
    "shower",                // 794
    "ski",                   // 795
    "ski",                   // 796
    "sleeping",              // 797
    "slide",                 // 798
    "sliding",               // 799
    "slot",                  // 800
    "snorkel",               // 801
    "snowmobile",            // 802
    "snowplow",              // 803
    "soap",                  // 804
    "soccer",                // 805
    "sock",                  // 806
    "solar",                 // 807
    "sombrero",              // 808
    "soup",                  // 809
    "space",                 // 810
    "space",                 // 811
    "space",                 // 812
    "spatula",               // 813
    "speedboat",             // 814
    "spider",                // 815
    "spindle",               // 816
    "check",                 // 817
    "spotlight",             // 818
    "stage",                 // 819
    "steam",                 // 820
    "steel",                 // 821
    "steel",                 // 822
    "stethoscope",           // 823
    "stole",                 // 824
    "stone",                 // 825
    "stopwatch",             // 826
    "stove",                 // 827
    "strainer",              // 828
    "check",                 // 829
    "stretcher",             // 830
    "studio",                // 831
    "stupa",                 // 832
    "submarine",             // 833
    "suit",                  // 834
    "sundial",               // 835
    "sunglass",              // 836
    "sunglasses",            // 837
    "sunscreen",             // 838
    "suspension",            // 839
    "swab",                  // 840
    "sweatshirt",            // 841
    "swimming",              // 842
    "swing",                 // 843
    "switch",                // 844
    "syringe",               // 845
    "table",                 // 846
    "tank",                  // 847
    "tape",                  // 848
    "teapot",                // 849
    "teddy",                 // 850
    "television",            // 851
    "tennis",                // 852
    "thatch",                // 853
    "theater",               // 854
    "thimble",               // 855
    "thresher",              // 856
    "throne",                // 857
    "tile",                  // 858
    "toaster",               // 859
    "tobacco",               // 860
    "toilet",                // 861
    "torch",                 // 862
    "totem",                 // 863
    "check",                 // 864
    "toyshop",               // 865
    "tractor",               // 866
    "check",                 // 867
    "tray",                  // 868
    "trench",                // 869
    "tricycle",              // 870
    "trimaran",              // 871
    "tripod",                // 872
    "triumphal",             // 873
    "check",                 // 874
    "trombone",              // 875
    "tub",                   // 876
    "turnstile",             // 877
    "typewriter",            // 878
    "umbrella",              // 879
    "unicycle",              // 880
    "upright",               // 881
    "vacuum",                // 882
    "vase",                  // 883
    "vault",                 // 884
    "velvet",                // 885
    "vending",               // 886
    "vestment",              // 887
    "viaduct",               // 888
    "violin",                // 889
    "volleyball",            // 890
    "waffle",                // 891
    "wall",                  // 892
    "wallet",                // 893
    "wardrobe",              // 894
    "warplane",              // 895
    "washbasin",             // 896
    "washer",                // 897
    "water",                 // 898
    "water",                 // 899
    "water",                 // 900
    "whiskey",               // 901
    "whistle",               // 902
    "wig",                   // 903
    "window",                // 904
    "window",                // 905
    "Windsor",               // 906
    "wine",                  // 907
    "wing",                  // 908
    "wok",                   // 909
    "wooden",                // 910
    "wool",                  // 911
    "worm",                  // 912
    "wreck",                 // 913
    "yawl",                  // 914
    "yurt",                  // 915
    "web",                   // 916
    "comic",                 // 917
    "crossword",             // 918
    "street",                // 919
    "traffic",               // 920
    "book",                  // 921
    "menu",                  // 922
    "plate",                 // 923
    "guacamole",             // 924
    "consomme",              // 925
    "hot",                   // 926
    "trifle",                // 927
    "ice",                   // 928
    "ice",                   // 929
    "French",                // 930
    "bagel",                 // 931
    "pretzel",               // 932
    "cheeseburger",          // 933
    "hotdog",                // 934
    "mashed",                // 935
    "head",                  // 936
    "broccoli",              // 937
    "cauliflower",           // 938
    "zucchini",              // 939
    "spaghetti",             // 940
    "acorn",                 // 941
    "butternut",             // 942
    "cucumber",              // 943
    "artichoke",             // 944
    "bell pepper",           // 945
    "cardoon",               // 946
    "mushroom",              // 947
    "Granny Smith",          // 948
    "strawberry",            // 949
    "orange",                // 950
    "lemon",                 // 951
    "fig",                   // 952
    "pineapple",             // 953
    "banana",                // 954
    "jackfruit",             // 955
    "custard",               // 956
    "pomegranate",           // 957
    "hay",                   // 958
    "carbonara",             // 959
    "chocolate sauce",       // 960
    "dough",                 // 961
    "meat",                  // 962
    "pizza",                 // 963
    "potpie",                // 964
    "burrito",               // 965
    "red",                   // 966
    "espresso",              // 967
    "cup",                   // 968
    "eggnog",                // 969
    "alp",                   // 970
    "bubble",                // 971
    "cliff",                 // 972
    "coral",                 // 973
    "geyser",                // 974
    "lakeside",              // 975
    "promontory",            // 976
    "sandbar",               // 977
    "seashore",              // 978
    "valley",                // 979
    "volcano",               // 980
    "ballplayer",            // 981
    "groom",                 // 982
    "scuba",                 // 983
    "rapeseed",              // 984
    "daisy",                 // 985
    "yellow",                // 986
    "corn",                  // 987
    "acorn",                 // 988
    "hip",                   // 989
    "buckeye",               // 990
    "coral",                 // 991
    "agaric",                // 992
    "gyromitra",             // 993
    "stinkhorn",             // 994
    "earthstar",             // 995
    "hen-of-the-woods",      // 996
    "bolete",                // 997
    "ear",                   // 998
    "toilet"                 // 999
};
